name: Deliver Tokens To Consumer

on:
  push:
    paths:
      - "src/tokens.json"

jobs:
  # Add a job for every additional consumer/application
  deliver_to_storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deliver Tokens To Storybook
        uses: andstor/copycat-action@v3
        with:
          # See documentation: https://docs.github.com/en/actions/reference/encrypted-secrets
          # Set the secret in the "src" repository
          personal_token: ${{ secrets.SEND_TO_STORYBOOK }}
          src_branch: main
          src_path: build/css/_variables.scss
          dst_owner: brockp
          dst_repo_name: suzy.exd.storybook
          dst_branch: main
          dst_path: src/tokens/_variables.css
          username: brockp
          email: brockp@suzy.com
          commit_message: Update tokens in storybook stylesheet, update Storybook story to reflect new tokens
