# .github/workflows/export-tokens-on-input.yml
name: Generate Tokens On Input From Figma

on:
  push:
    paths:
      - "src/input/*.json"

jobs:
  generate_tokens:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: "16"
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install Node Dependencies
        run: npm install
      - name: Transform & Expand Input
        run: npm run transform
      - name: Build Style Dictionary
        run: npm run build-custom
      - name: Commit Generated Platform Deliverables
        id: "auto-commit-action"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update design tokens from Figma
